### ISSUE TITLE
Sugestões de melhoria

### ISSUE THREAD

**Issue by JosueFS** [viniciussoares7/CalculaThor#1]
Adicionar um padding à direita do elemento "p.show" para ter um distanciamento da borda:
![image](https://user-images.githubusercontent.com/45906601/124314743-38626480-db49-11eb-892d-207a762d0a8a.png)

Adicionar um max-width para evitar de quebrar quando tiver um número excedente de caracteres que não caiba no elemento "p.show", também pode adicionar uma formatação pra limitar os caracteres após a virgula pra evitar esses excedente em resultados de alguns cálculos:
![image](https://user-images.githubusercontent.com/45906601/124314635-179a0f00-db49-11eb-86e7-f27864c3257c.png)

**Comment by viniciussoares7** [comment]
Prontinho, resolvi essas questões já. Muito obrigado pelas sugestões!! :metal: :metal:

**Comment by viniciussoares7** [comment]
> Adicionar um padding à direita do elemento "p.show" para ter um distanciamento da borda:
> 
> 
> Adicionar um max-width para evitar de quebrar quando tiver um número excedente de caracteres que não caiba no elemento "p.show", também pode adicionar uma formatação pra limitar os caracteres após a virgula pra evitar esses excedente em resultados de alguns cálculos:

--------------------------

Prontinho, resolvi essas questões já. Muito obrigado pelas sugestões!! 🤘 🤘 @JosueFS

**Comment by JosueFS** [comment]
Show, agora vou fechar a issue porque você já resolveu! rs
